export const data:any= {
    "PAYMENT TERM": [
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-22T12:08:01.074Z",
        "updatedTimestamp": "2023-11-25T06:46:43.561Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "69ab6010-e8be-4f66-b1c9-82f751d75aa8",
        "clauseCode": "PAYMENT TERM 1",
        "clauseHeading": "PAYMENT TERM",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "100% SIGHT IRREVOCABLE UNRESTRICTED LETTER OF CREDIT TO BE ISSUED BY A FIRST CLASS BANK IN CHINA 7 DAYS BEFORE SHIPMENT.",
        "tradeTransactionType": null
      },
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-22T07:46:42.148Z",
        "updatedTimestamp": "2023-11-24T10:43:53.925Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "a8b1df00-716f-4945-b4e3-fc70c87235c5",
        "clauseCode": "PAYMENT TERM 2",
        "clauseHeading": "PAYMENT TERM",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "ALL PORT FORMALITIES AT DISCHARGE PORT(S) AND IMPORT DUTIES/TAXES/LEVIES SHALL BE AT BUYER'S ACCOUNT. \n",
        "tradeTransactionType": null
      }
    ],
    "DEMURRAGE": [
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-22T07:48:26.612Z",
        "updatedTimestamp": "2023-11-24T10:46:45.343Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "800c67a9-d6fa-4b97-a661-c96886fb696f",
        "clauseCode": "DEMURRAGE 1",
        "clauseHeading": "DEMURRAGE",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "IN THE ABSENCE OF ORIGINAL DOCUMENTS AT DISCHARGE PORT, THE BUYER UNDERTAKES TO ISSUE COMPANY'S LOI (WORDED IN THE SAME FORMAT OF THE SHIPOWNER'S P&I CLUB TO BE PROVIDED BY THE SHIPOWNER THROUGH THE SELLER) IN FAVOUR OF THE SHIPOWNER. THE COMPANY'S LOI LOI IS TO BE ARRANGED IMMEDIATELY UPON VESSEL'S SAILING-OFF FROM THE LOADING PORT AND TO BE READILY AVAILABLE 48 HOURS BEFORE THE SAME VESSEL'S ESTIMATED TIME OF ARRIVAL AT DISCHARGE PORT. FAILLING WHICH, BUYER WILL BE HELD REPONSIBLE FOR ANY LOST TIME/DEMURRAGE OR OTHER COSTS RESULTED BY THE DELAY IN CUSTOMS CLEARANCE AND/OR DISCHARGING OF THE CARGOES.",
        "tradeTransactionType": null
      },
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "rama",
        "createdTimestamp": "2023-11-23T11:43:16.518Z",
        "updatedTimestamp": "2023-11-30T11:57:06.520Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "a45486ef-5647-4e45-bfd5-7fbfe9fdb0a7",
        "clauseCode": "DEMURRAGE 2",
        "clauseHeading": "DEMURRAGE",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": false,
        "clauseDescription": "DEMURRAGE IF ANY AT DISCHARGE PORT SHALL BE FOR BUYER'S ACCOUNT AS PER CHARTER PARTY TERMS. BUYER TO SETTLE DEMURRAGE WITHIN THIRTY DAYS AFTER RECEIPT OF SELLER'S DEMURRAGE INVOICE.",
        "tradeTransactionType": null
      },
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-23T12:22:03.398Z",
        "updatedTimestamp": "2023-11-24T06:47:02.550Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "899a54a5-08f9-4e61-9083-bc08744aa2ff",
        "clauseCode": "DEMURRAGE 3",
        "clauseHeading": "DEMURRAGE",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "1. SIGNED COMMERCIAL INVOICE IN 3 ORIGINALS. \n2. FULL SET OF CLEAN ON BOARD OCEAN SHIPPING BILLS OF LADING CONSIGNED\n   TO ORDER, BANK ENDORSED, MARKED \"FREIGHT PREPAID\"/ \"FREIGHT PAID\" AND \n   NOTIFY RELEVANT PARTY, IN 3 ORIGINALS AND 3 COPIES. \n3. CERTIFICATE OF WEIGHT AND QUALITY ISSUED BY ANY INDEPENDENT \n   SURVEYOR OR SUPERINTENDENT COMPANY. \n4. CERTIFICATE OF SHIP'S TANKS, PUMPS AND PIPES IN 1 ORIGINAL \n   ISSUED BY AN INDEPENDENT \n   SURVEYOR EVIDENCING THAT THE TANKS , PUMPS , AND PIPES ARE SUITABLE\n   TO RECEIVE AND CARRY THE OIL.\n",
        "tradeTransactionType": null
      },
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-23T12:24:41.405Z",
        "updatedTimestamp": "2023-11-24T06:59:08.289Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "0d740903-8137-407e-b77a-6b2d847c19b9",
        "clauseCode": "DEMURRAGE 4",
        "clauseHeading": "DEMURRAGE",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "TO BE FAXED AND COURIED TO BUYER DIRECTLY: \n1. CERTIFICATE OF ORIGIN BY GOVERNMENT AUTHORITY OR CHAMBER OF COMMERCE \n   IN 1 ORIGINAL AND 2 COPIES. \n2. HEALTH / SANITARY CERTIFICATE ISSUED BY GOVERNMENT DEPARTMENT \n   IN 1 ORIGINAL AND 2 COPIES. \n3. PHYTOSANITARY CERTIFICATE ISSUED BY OFFICIAL RELEVANT AUTHORITY IN ORIGINAL AND 2 COPIES.\n",
        "tradeTransactionType": null
      },
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-24T05:25:24.662Z",
        "updatedTimestamp": "2023-11-24T06:45:44.427Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "b2d4cfcb-eb06-4b19-a0c1-c0fec799e0cf",
        "clauseCode": "DEMURRAGE 5",
        "clauseHeading": "DEMURRAGE",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "BUYER TO GUARANTEE MINIMUM DISCHARGE RATE OF 100 MTPH SATURDAY, SUNDAY AND HOLIDAYS INCLUDED (SHINC). LAYTIME TO START COUNTING 6 HOURS AFTER NOR BEING TENDERED WIBON, WIFPON, WICCON, WIPON OR IMMEDIATELY UPON VESSEL BERTHING WHICHEVER IS EARLIER. NOR TENDERED BY FACSIMILE, TELEX, TELEGRAPH, WIRELESS LETTER OR TELEPHONE (OR ANY METHOD ALLOWED BY THE CHARTER PARTY) IS ACCEPTABLE OF SELLER'S DEMURRAGE INVOICE.\n\n",
        "tradeTransactionType": null
      },
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-22T08:04:34.440Z",
        "updatedTimestamp": "2023-11-24T06:49:40.277Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "047bd4ba-346d-4d9a-a424-c2171674e4fc",
        "clauseCode": "DEMURRAGE 6",
        "clauseHeading": "DEMURRAGE",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "1.BUYER UNDERTAKES THAT THE COMMODITY WILL NOT BE RESOLD TO, DISPOSED OF, OR DELIVERED TO ANY COUNTRY, PERSON OR ENTITY WHICH WOULD CAUSED THE SELLER TO BE IN VIOLATION OF OR BE PENALISED BY ANY APPLICABLE TRADE CONTROL LAWS. \n2.WITHOUT PREJUDICE TO ANY OTHER RIGHTS THAT THE SELLER MAY HAVE, IN THE EVENT OF ANY FAILURE TO COMPLY WITH ITS UNDERTAKINGS OR IF THE SELLER HAS REASONABLE GROUNDS FOR BELIEVEING THAT THE BUYER HAS FAILED TO OR WILL NOT COMPLY WITH SUCH UNDERTAKINGS, THE SELLER MAY AT ITS SOLE DISCRETION, TERMINATE THIS CONTRACT FORTHWITH OR FORHWITH SUSPEND DELIVERY UNDER THIS CONTRACT UNTIL FURTHER NOTICE OR DECLINE TO COMMENCE OR COMPLETE LOADING HEREUNDER ON NOTIFYING THE BUYER EITHER IN WRITTING OR ORALLY (WITH WRITTEN CONFIRMATION TO FOLLOW). \n3.THE BUYER SHALL INDEMNIFY AND HOLD THE SELLER HARMLESS FOR ANY COSTS, LIABILITES, PENALTIES, INTERESTS, DAMAGES OR ANY OTHER LOSSES SUFFERED OR INCURRED BY THE SELLER IN THE EVENT OF A BREACH OF THE SANCTIONS CLAUSE BY THE BUYER OR NON COMPLIANCE OF ANY APLLICABLE TRADE CONTROLS LAWS BY THE BUYER.\n",
        "tradeTransactionType": null
      }
    ],
    "ASSIGNMENT": [
      {
        "username": null,
        "createdBy": "Jaddu",
        "updatedBy": "Jaddu",
        "createdTimestamp": "2023-11-24T06:00:46.087Z",
        "updatedTimestamp": "2023-11-24T06:45:55.862Z",
        "token": null,
        "code": null,
        "validFrom": null,
        "validTo": null,
        "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
        "uuid": "8722d619-a7a7-4cbb-a148-f9fdb3af2b93",
        "clauseCode": "ASSIGNMENT 1",
        "clauseHeading": "ASSIGNMENT",
        "country": null,
        "counterParty": null,
        "company": null,
        "commodity": null,
        "contractTerm": null,
        "paymentTerm": null,
        "incoterm": null,
        "clauseCategory": "Contract",
        "clauseSubCategory": null,
        "status": true,
        "docGenEdit": true,
        "clauseDescription": "NO ASSIGNMENT OF THIS CONTRACT, IN WHOLE OR IN PART, WILL BE MADE WITHOUT THE PRIOR WRITTEN CONSENT OF THE NON-ASSIGNING PARTY (AND SHALL NOT RELIEVE THE ASSIGNING PARTY FROM LIABILITY HEREUNDER), WHICH CONSENT WILL NOT BE UNREASONABLY WITHHELD OR DELAYED. UPON ANY SUCH ASSIGNMENT, TRANSFER OR ASSUMPTION, THE TRANSFEROR SHALL REMAIN PRINCIPALLY LIABLE FOR AND SHALL NOT BE RELIEVED OF OR DISCHARGED FROM ANY OBLIGATIONS HEREUNDER.\n",
        "tradeTransactionType": null
      }
    ]
    // "SANCTIONS CLAUSE": [
    //   {
    //     "username": null,
    //     "createdBy": "Jaddu",
    //     "updatedBy": "Jaddu",
    //     "createdTimestamp": "2023-11-23T10:21:14.964Z",
    //     "updatedTimestamp": "2023-11-24T06:48:10.822Z",
    //     "token": null,
    //     "code": null,
    //     "validFrom": null,
    //     "validTo": null,
    //     "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
    //     "uuid": "29e5839b-ff62-4775-8f2a-892fa10da326",
    //     "clauseCode": "ALL CHINA-BANGLA_ SANCTION CLAUSE",
    //     "clauseHeading": "SANCTIONS CLAUSE",
    //     "country": null,
    //     "counterParty": null,
    //     "company": null,
    //     "commodity": null,
    //     "contractTerm": null,
    //     "paymentTerm": null,
    //     "incoterm": null,
    //     "clauseCategory": "Contract",
    //     "clauseSubCategory": null,
    //     "status": true,
    //     "docGenEdit": true,
    //     "clauseDescription": "1.COMPLIANCE WITH LAWS \n(A)BUYER AND SELLER MUST, IN PERFORMING THIS AGREEMENT, COMPLY WITH APPLICABLE TRADE CONTROL LAWS. \n(B)BUYER AND SELLER EACH REPRESENT AND WARRANT TO THE OTHER THAT IT IS NOT A SANCTIONED ENTITY. \n(C)SELLER EXPRESSLY WARRANTS THAT TO THE BEST OF ITS KNOWLEDGE AND BELIEF, THE PRODUCT TO BE SUPPLIED UNDER THIS AGREEMENT, WHETHER IN WHOLE OR IN PART, DOES NOT ORIGINATE FROM A SANCTIONED COUNTRY OR SANCTIONED TERRITORY WHERE THE EXPORT OF SUCH PRODUCT IS IN CONTRAVENTION OF APPLICABLE TRADE CONTROLS LAWS OR FROM A SANCTIONED ENTITY, AND SELLER FURTHER WARRANTS THAT THE PRODUCT TO BE SUPPLIED UNDER THIS AGREEMENT HAS NOT BEEN EXPORTED/PROCURED FROM A SANCTIONED COUNTRY, SANCTIONED TERRITORY OR SANCTIONED ENTITY THROUGH INTERMEDIARIES OR OTHERWISE. \n(D)BUYER WARRANTS THAT SELLER SHALL NOT BE IN BREACH OF ANY APPLICABLE TRADE CONTROL LAWS BY REASON OF SELLER'S DELIVERY OF PRODUCT TO THE VESSEL NOMINATED BY BUYER (WHETHER BY REASON OF THE VESSEL'S OWNERSHIP, FLAG STATE, CREW COMPOSITION, TRADING HISTORY, LAST PORT OF CALL, NEXT INTENDED PORT OF CALL OR OTHERWISE HOWSOEVER) AND BUYER SPECIFICALLY WARRANTS THAT THE VESSEL IS NOT OWNED, MANAGED, CHARTERED OR CONTROLLED BY A SANCTIONED ENTITY. \n(E)IN THIS AGREEMENT, THE FOLLOWING TERMS AND PHRASES HAVE THE MEANINGS STIPULATED HEREUNDER: \n\n2.\"APPLICABLE TRADE CONTROL LAWS\" ANY SANCTIONS, EXPORT CONTROL, OR IMPORT LAWS, OR OTHER REGULATIONS, ORDERS, DIRECTIVES, DESIGNATIONS, LICENSES, OR DECISIONS RELATING TO THE TRADE OF GOODS AND SERVICES WHICH ARE IMPOSED, ADMINISTERED OR ENFORCED FROM TIME TO TIME BY THE UNITED STATES OF AMERICA, THE UNITED KINGDOM, THE EUROPEAN UNION, THE MEMBER STATES OF THE EUROPEAN UNION, SWITZERLAND, THE UNITED NATIONS OR UNITED NATIONS SECURITY COUNCIL, OR ANY OTHER COUNTRY WITH JURISDICTION OVER ACTIVITIES UNDERTAKEN IN CONNECTION WITH THIS AGREEMENT. \n\n3.\"SANCTIONED COUNTRY\" OR \"SANCTIONED TERRITORY\" \n(A)IRAN, NORTH KOREA AND SYRIA; AND \n(B)ANY COUNTRY OR TERRITORY AGAINST WHICH SANCTIONS ARE IMPOSED, ADMINISTERED OR ENFORCED FROM TIME TO TIME BY THE UNITED STATES OF AMERICA, THE UNITED KINGDOM, THE EUROPEAN UNION, ANY MEMBER STATE OF THE EUROPEAN UNION, SWITZERLAND, THE UNITED NATIONS OR UNITED NATIONS SECURITY COUNCIL, OR ANY OTHER COUNTRY WITH JURISDICTION OVER THE ACTIVITIES UNDERTAKEN IN CONNECTION WITH THIS AGREEMENT. \n\n4.\"SANCTIONED ENTITY\" \n(A)ANY PERSON OR ENTITY THAT IS DESIGNATED FOR EXPORT CONTROLS OR SANCTIONS RESTRICTIONS UNDER ANY APPLICABLE TRADE CONTROLS LAWS, INCLUDING BUT NOT LIMITED TO THOSE DESIGNATED UNDER THE U.S. LIST OF SPECIALLY DESIGNATED NATIONALS AND BLOCKED PERSONS, FOREIGN SANCTIONS EVADERS LIST, ENTITY LIST, DENIED PERSONS LIST, DEBARRED LIST, THE UK CONSOLIDATED LIST AND THE EU CONSOLIDATED LIST OF PERSONS, GROUPS, AND ENTITIES SUBJECT TO EU FINANCIAL SANCTIONS; AND \n(B)ANY ENTITY 50% OR MORE OWNED OR ANY ENTITY WHICH IS CONTROLLED, DIRECTLY OR INDIRECTLY, BY ONE OR MORE OF THE PERSONS OR ENTITIES IN PARAGRAPH (A).\n\n",
    //     "tradeTransactionType": null
    //   }
    // ],
    // "OTHER TERMS AND CONDITIONS": [
    //   {
    //     "username": null,
    //     "createdBy": "Jaddu",
    //     "updatedBy": "Jaddu",
    //     "createdTimestamp": "2023-11-24T07:36:04.743Z",
    //     "updatedTimestamp": "2023-11-24T12:16:45.204Z",
    //     "token": null,
    //     "code": null,
    //     "validFrom": null,
    //     "validTo": null,
    //     "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
    //     "uuid": "b648bc97-93a0-4829-a698-a0a9e5d09ffe",
    //     "clauseCode": "ALL CHINA-BANGLA_OTC",
    //     "clauseHeading": "OTHER TERMS AND CONDITIONS",
    //     "country": null,
    //     "counterParty": null,
    //     "company": null,
    //     "commodity": null,
    //     "contractTerm": null,
    //     "paymentTerm": null,
    //     "incoterm": null,
    //     "clauseCategory": "Contract",
    //     "clauseSubCategory": null,
    //     "status": true,
    //     "docGenEdit": true,
    //     "clauseDescription": "1. THIRD PARTY DOCUMENTS ACCEPTABLE EXCEPT INVOICE. \n2. THIRD PARTY DOCUMENTS LIKE CERTIFICATE OF ORIGIN AND SURVEYOR REPORT \n   SHOWING EXPORTER/SHIPPER DIFFER FROM BENEFICIARY ACCEPTABLE. \n3. CHARTER PARTY/BLANK BACK/TANKER/THIRD PARTY BILL OF LADING ACCEPTABLE. \n4. COMMINGLING WITH THE SAME GRADE OF OIL ALLOWED. \n5. THIS CONTRACT IS GOVERNED BY INCOTERM 2010. \n6. ALL OTHER TERMS AND CONDITIONS WHERE NOT IN CONTRADICTION TO ANY OF THE \n   TERMS AND CONDITIONS OF \n   THIS CONTRACT SHALL BE IN ACCORDANCE WITH FOSFA 81 CURRENTLY IN FORCE. \n   IN THE EVENT OF ANY INCONSISTENCY BETWEEN THE TERMS OF THIS CONTRACT \n   AND THE TERMS OF FOSFA 81, THE TERMS OF THIS CONTRACT SHALL PREVAIL. \n7. BUYER IS NOT ALLOWED TO ASSIGN THIS SALES CONTRACT TO ANY THIRD PARTY\n    WITHOUT PRIOR WRITTEN CONSENT FROM SELLER\n   \n",
    //     "tradeTransactionType": null
    //   }
    // ],
    // "Testing": [
    //   {
    //     "username": null,
    //     "createdBy": "Srujan",
    //     "updatedBy": "Srujan",
    //     "createdTimestamp": "2024-02-02T11:32:13.857Z",
    //     "updatedTimestamp": "2024-02-02T11:32:13.857Z",
    //     "token": null,
    //     "code": null,
    //     "validFrom": null,
    //     "validTo": null,
    //     "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
    //     "uuid": "07cdc23c-2c27-488e-8085-c99d0e300043",
    //     "clauseCode": "Test",
    //     "clauseHeading": "Testing",
    //     "country": null,
    //     "counterParty": null,
    //     "company": null,
    //     "commodity": null,
    //     "contractTerm": null,
    //     "paymentTerm": null,
    //     "incoterm": null,
    //     "clauseCategory": "Contract",
    //     "clauseSubCategory": null,
    //     "status": true,
    //     "docGenEdit": true,
    //     "clauseDescription": "Creating new clause",
    //     "tradeTransactionType": null
    //   }
    // ],
    // "OTC": [
    //   {
    //     "username": null,
    //     "createdBy": "bhima",
    //     "updatedBy": "bhima",
    //     "createdTimestamp": "2024-02-07T07:04:06.948Z",
    //     "updatedTimestamp": "2024-02-07T07:32:32.243Z",
    //     "token": null,
    //     "code": null,
    //     "validFrom": null,
    //     "validTo": null,
    //     "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
    //     "uuid": "3cf5cbb5-5dfb-4f5e-832e-3174365ba105",
    //     "clauseCode": "Clause1",
    //     "clauseHeading": "OTC ",
    //     "country": null,
    //     "counterParty": null,
    //     "company": null,
    //     "commodity": null,
    //     "contractTerm": null,
    //     "paymentTerm": null,
    //     "incoterm": null,
    //     "clauseCategory": "Contract",
    //     "clauseSubCategory": null,
    //     "status": true,
    //     "docGenEdit": true,
    //     "clauseDescription": "OTC; test",
    //     "tradeTransactionType": null
    //   }
    // ],
    // "Bank Details": [
    //   {
    //     "username": null,
    //     "createdBy": "deepika",
    //     "updatedBy": "deepika",
    //     "createdTimestamp": "2024-05-16T12:45:41.641Z",
    //     "updatedTimestamp": "2024-05-16T12:45:41.641Z",
    //     "token": null,
    //     "code": null,
    //     "validFrom": null,
    //     "validTo": null,
    //     "tenantId": "d7408d31-d720-4173-b76e-0595ce2679b4",
    //     "uuid": "92c9cd63-8ad6-470a-a170-14881fe4ee6f",
    //     "clauseCode": "Bank Details",
    //     "clauseHeading": "Bank Details",
    //     "country": null,
    //     "counterParty": null,
    //     "company": null,
    //     "commodity": null,
    //     "contractTerm": null,
    //     "paymentTerm": null,
    //     "incoterm": null,
    //     "clauseCategory": "Contract",
    //     "clauseSubCategory": null,
    //     "status": true,
    //     "docGenEdit": true,
    //     "clauseDescription": "Bank Details:",
    //     "tradeTransactionType": null
    //   }
    // ]
  }